[build]
builder = "nixpacks"
[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn mysite.wsgi"

[phases.setup]
nixPkgs = ["postgresql16Packages.postgis"]
